src/Entity/User.php
<?php

namespace App\Entity;

use App\Constant\Constant;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\EquatableInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="`app_user`")
 * @UniqueEntity("username", message="Identifiant déjà utilisé")
 * @UniqueEntity("email", message="Email déjà utilisé")
 * @UniqueEntity("slug", message="Slug déjà utilisé")
 */
class User implements UserInterface, EquatableInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=32, unique=true)
     * @Assert\Regex(
     *     pattern="/^[a-zA-Zà-źÀ-Ź0-9]+$/",
     *     match=true,
     *     message="L'identifiant est constitué de lettres et chiffres uniquement"
     * )
     */
    private $username;

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=256, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=32, unique=true)
     * @Assert\Regex(
     *     pattern="/^[a-zA-Z0-9]+$/",
     *     match=true,
     *     message="Le slug est constitué de lettres sans accent et chiffres uniquement"
     * )
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=32)
     */
    private $role;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $connected_at;

    /**
     * @ORM\Column(type="string", length=32, nullable=true)
     */
    private $wallpaper;

    /**
     * @ORM\OneToMany(targetEntity=Page::class, mappedBy="user", orphanRemoval=true)
     * @ORM\OrderBy({"z" = "ASC", "created_at" = "ASC"})
     */
    private $pages;

    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->slug       = str_replace('.', '', uniqid('BM', true));
        $this->pages      = new ArrayCollection();
        $this->wallpaper  = Constant::WALLPAPERS['Business'];
    }

    public function __toString()
    {
        return $this->username;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(?string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles[] = $this->role;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(?string $password): self
    {
        if (!is_null($password)) {
            $this->password = $password;
        }

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = mb_strtolower($email);

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getRole(): ?string
    {
        return $this->role;
    }

    public function setRole(string $role): self
    {
        $this->role = $role;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getConnectedAt(): ?\DateTimeInterface
    {
        return $this->connected_at;
    }

    public function setConnectedAt(?\DateTimeInterface $connected_at): self
    {
        $this->connected_at = $connected_at;

        return $this;
    }

    public function getWallpaper(): ?string
    {
        return $this->wallpaper;
    }

    public function setWallpaper(?string $wallpaper): self
    {
        $this->wallpaper = $wallpaper;

        return $this;
    }

    /**
     * @return Collection|Page[]
     */
    public function getPages(): Collection
    {
        return $this->pages;
    }

    public function addPage(Page $page): self
    {
        if (!$this->pages->contains($page)) {
            $this->pages[] = $page;
            $page->setUser($this);
        }

        return $this;
    }

    public function removePage(Page $page): self
    {
        if ($this->pages->removeElement($page)) {
            // set the owning side to null (unless already changed)
            if ($page->getUser() === $this) {
                $page->setUser(null);
            }
        }

        return $this;
    }

    /**
     * La méthode sera appelée lors de la comparaison des utilisateurs afin de vérifier s'il nécessaire de forcer
     * l'utilisateur à se reconnecter.
     * L'implémentation de cette méthode permet d'éviter les déconnexions intempestives (voir exemples cités ci-dessous).
     *
     * @link https://stackoverflow.com/questions/63924686/symfony5-update-user-profile-cause-logout-when-edit-form-submitted
     * @link https://github.com/symfony/symfony/issues/33418
     */
    public function isEqualTo(UserInterface $user): bool
    {
        if (!$user instanceof self) {
            return false;
        }

        if ($this->getId() !== $user->getId()) {
            return false;
        }

        return true;
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Util\MailService;

use App\Constant\Constant;
use App\Util\CaptchaService;
use App\Repository\UserRepository;
use App\Validator\CaptchaConstraint;
use Symfony\Component\Form\FormError;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\Email;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class UserController extends AbstractController
{
    #[Route('users', name: 'user_index', methods: ['GET'])]
    public function index(UserRepository $userRepository): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    #[Route('sign-up', name: 'user_new', methods: ['GET', 'POST'])]
    public function new(Request $request, UserPasswordEncoderInterface $encoder, CaptchaService $captchaService): Response
    {
        $this->denyAccessUnlessGranted('IS_ANONYMOUS');

        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user->setRole('ROLE_USER');
            $user->setPassword($encoder->encodePassword($user, $user->getPassword()));
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($user);
            $entityManager->flush();

            $this->addFlash(
                'success',
                Constant::SUCCESS_SIGN_UP
            );

            return $this->redirectToRoute('app_login');
        }

        return $this->render('user/new.html.twig', [
            'user'    => $user,
            'captcha' => $captchaService->createCaptcha(),
            'form'    => $form->createView(),
        ]);
    }

    #[Route('user/{id}/edit', name: 'user_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, User $user, UserPasswordEncoderInterface $encoder): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_REMEMBERED');

        if ($this->getUser()->getId() !== $user->getId() && $this->getUser()->getRole() !== 'ROLE_ADMIN') {
            $this->addFlash(
                'danger',
                Constant::FORBIDDEN
            );
            return $this->redirectToRoute('dashboard');
        }

        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ($this->getUser()->getId() !== $user->getId() && $this->getUser()->getRole() !== 'ROLE_ADMIN') {
                $this->addFlash(
                    'danger',
                    Constant::FORBIDDEN
                );
                return $this->redirectToRoute('dashboard');
            }

            if (!is_null($form->get('password')->getData())) {
                $user->setPassword($encoder->encodePassword($user, $user->getPassword()));
            }
            $this->getDoctrine()->getManager()->flush();

            $this->addFlash(
                'success',
                Constant::SUCCESS_ACTION
            );

            return $this->redirectToRoute('dashboard');
        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    #[Route('user/delete/{id}', name: 'user_delete', methods: ['GET'])]
    public function delete(Request $request, User $user): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        // Un compte utilisateur ADMIN ne peut pas être supprimé
        if ($user->getRole() === 'ROLE_ADMIN') {
            $this->addFlash(
                'danger',
                Constant::UNAUTHORIZED
            );
            return $this->redirectToRoute('dashboard');
        }
        
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->query->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($user);
            $entityManager->flush();
        }

        $this->addFlash(
            'success',
            Constant::SUCCESS_ACTION
        );

        return $this->redirectToRoute('dashboard');
    }

    #[Route('/forgot-password', name: 'forgot_password', methods: ['GET', 'POST'])]
    public function forgotPassword(Request $request, UserRepository $userRepository, MailService $emailService, UserPasswordEncoderInterface $encoder, CaptchaService $captchaService): Response
    {
        $this->denyAccessUnlessGranted('IS_ANONYMOUS');

        $form = $this->createForgotPasswordForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();
            $user = $userRepository->findOneBy([
                'username' => $data['username'],
                'email'    => $data['email']
            ]);

            if (is_null($user)) {
                $form->addError(new FormError(Constant::ERROR_NO_MATCHING_USER));
                return $this->render('user/forgot_password.html.twig', [
                    'captcha' => $captchaService->createCaptcha(),
                    'form'    => $form->createView()
                ]);
            }

            $newPassword = uniqid();
            $user->setPassword($encoder->encodePassword($user, $newPassword));
            $this->getDoctrine()->getManager()->flush();

            (array) $res = $emailService->sendEmail($user->getEmail(), Constant::EMAIL_FORGOT_PASSWORD_SUBJECT, str_replace('[NEW_PASSWORD]', $newPassword, Constant::EMAIL_FORGOT_PASSWORD_TEXT), str_replace('[NEW_PASSWORD]', $newPassword, Constant::EMAIL_FORGOT_PASSWORD_HTML));

            $this->addFlash(
                $res['success'] ? 'success' : 'danger',
                $res['message']
            );

            return $this->redirectToRoute('app_login');
        }

        return $this->render('user/forgot_password.html.twig', [
            'captcha' => $captchaService->createCaptcha(),
            'form'    => $form->createView()
        ]);

        return $this->redirectToRoute('dashboard');
    }

    private function createForgotPasswordForm()
    {
        return $this->createFormBuilder(null, ['method' => 'POST'])
            ->add('username', TextType::class, [
                'label'       => 'Identifiant (*)',
                'attr'        => ['placeholder' => 'Identifiant'],
                'constraints' => [
                    new NotBlank([
                        'message' => Constant::CONSTRAINT_MESSAGE_NOT_BLANK
                    ]),
                    new Length([
                        'max'        => 60,
                        'maxMessage' => Constant::CONSTRAINT_MESSAGE_MAX_LENGTH . '{{ limit }}'
                    ])
                ]
            ])
            ->add('email', EmailType::class, [
                'label' => 'Email (*)',
                'help'  => Constant::HELP_FORGOT_PASSWORD_MESSAGE,
                'attr'  => [
                    'placeholder' => 'exemple@gmail.com'
                ],
                'constraints' => [
                    new NotBlank([
                        'message' => Constant::CONSTRAINT_MESSAGE_NOT_BLANK
                    ]),
                    new Email([
                        'mode'    => 'loose',
                        'message' => Constant::CONSTRAINT_MESSAGE_INVALID_EMAIL
                    ]),
                    new Length([
                        'min'        => 5,
                        'max'        => 250,
                        'minMessage' => Constant::CONSTRAINT_MESSAGE_MIN_LENGTH . '{{ limit }}',
                        'maxMessage' => Constant::CONSTRAINT_MESSAGE_MAX_LENGTH . '{{ limit }}'
                    ])
                ]
            ])->add('captcha', IntegerType::class, [
                'label'       => Constant::CAPTCHA_LABEL,
                'mapped'      => false,
                'constraints' => [
                    new NotBlank([
                        'message' => Constant::CONSTRAINT_MESSAGE_NOT_BLANK
                    ]),
                    new Length([
                        'min'        => 4,
                        'max'        => 4,
                        'minMessage' => Constant::CONSTRAINT_MESSAGE_MIN_LENGTH . '{{ limit }}',
                        'maxMessage' => Constant::CONSTRAINT_MESSAGE_MAX_LENGTH . '{{ limit }}'
                    ]),
                    new CaptchaConstraint()
                ]
            ])->getForm();
    }
}

templates/user/_form.html.twig
<div class="col-12">
    {{ form_start(form, {'attr': {'novalidate': 'novalidate', 'class': 'col-sm-6 mx-auto'}}) }}
        <div class="my-custom-class-for-errors">
            {{ form_errors(form) }}
        </div>
        {# {{ form_widget(form) }} #}
        {{ form_row(form.username) }}
        {{ form_row(form.email) }}

        {% if app.request.get('_route') != 'forgot_password' %}
            {{ form_row(form.password) }}
        {% endif %}

        {% if app.user and app.user.role == 'ROLE_ADMIN' and app.user.id != user.id %}
            {{ form_row(form.slug) }}
            {{ form_row(form.role) }}
        {% endif %}

        {# Gestion affichage du captcha #}
        {% if captcha is defined %}
            <p><img src="{{ 'data:image/jpeg;base64,' ~ captcha }}" class="img-fluid" alt="captcha" title="captcha"></p>
            {{ form_row(form.captcha) }}
        {% endif %}

        <div class="modal-footer">
            {% if app.user %}
                <a class="btn btn-secondary" href="{{ path('dashboard') }}">{{ Constant.BACK_TO_LIST }}</a>
            {% else %}
                <a class="btn btn-secondary" href="{{ path('app_login') }}">{{ Constant.BACK }}</a>
            {% endif %}
            <input class="btn btn-dark" type="submit" value="{{ Constant.SUBMIT_ACTION }}">
        </div>
    {{ form_end(form) }}
</div>

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ Constant.USER_UPDATE_LABEL }}{% endblock %}

{% block body %}
    <h1 class="col-12 text-light text-center">{{ Constant.USER_UPDATE_LABEL }}</h1>

    {{ include('user/_form.html.twig') }}
{% endblock %}

templates/user/forgot_password.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ Constant.FORGOT_PASSWORD }}{% endblock %}

{% block body %}

        <h1 class="text-dark mx-auto mt-3">{{ Constant.FORGOT_PASSWORD }}</h1>
        {{ include('user/_form.html.twig') }}

{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ Constant.USER_INDEX_LABEL }}{% endblock %}

{% block body %}
    <div class="col-11 mx-auto customTableContainer">
        <h1 class="text-light">{{ Constant.USER_INDEX_LABEL }}</h1>

        <table class="table">
            <thead>
                <tr>
                    <th>Identifiant</th>
                    <th>Email</th>
                    <th>Rôle</th>
                    <th>Créé le</th>
                    <th>Connecté le</th>
                    <th>Stats</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
            {% for user in users %}
                <tr>
                    <td>{{ user.id }} @ {{ user.username }}</td>
                    <td>{{ user.email }}</td>
                    <td>{{ user.role == 'ROLE_ADMIN' ? 'Administrateur' : 'Utilisateur' }}</td>
                    <td>{{ user.createdAt ? user.createdAt|date('d/m/Y à H:i:s') : '' }}</td>
                    <td>{{ user.connectedAt ? user.connectedAt|date('d/m/Y à H:i:s') : '' }}</td>
                    <td>
                        Pages : {{ user.pages|length }}
                    </td>
                    <td>
                        <a href="{{ path('user_edit', {'id': user.id}) }}"><i class="fas fa-pen"></i></a>
                        {% if user.role != 'ROLE_ADMIN' %}
                            <a href="{{ path('user_delete', {'id': user.id}) }}?_token={{ csrf_token('delete' ~ user.id) }}" 
                            class="userDeleteBtn">
                                <i class="fas fa-trash-alt"></i>
                            </a>
                        {% endif %}
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="9">{{ Constant.NO_RECORDS_FOUND }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <p class="col-12 text-center">
            <a class="btn btn-dark" href="{{ path('dashboard') }}">{{ Constant.BACK }}</a>
        </p>
    </div>
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('assets/js/userDelete.js') }}{{ assets_version }}"></script>
{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ Constant.USER_NEW_LABEL }}{% endblock %}

{% block body %}
    <h1>{{ Constant.USER_NEW_LABEL }}</h1>

    {{ include('user/_form.html.twig') }}

{% endblock %}